version: '1.0'

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"
    environment:
      NODE_ENV: production
    container_name: square-off-js-app
